name: betacast
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - cftime
  - matplotlib
  - netCDF4
  - cfgrib
  - numba
  - numpy
  - scipy
  - scikit-learn
  - xarray
  - ncl
  - nco
